if: type = pull_request

language: cpp
dist: xenial

cache: ccache

# Check clang format in the first stage
before_install: sh .travis/before_install.sh
script: sh .travis/check_clang_format.sh

# Then start parallel build of gcc and clang
matrix:
  include:
    - compiler: gcc
      before_install: sh .travis/before_install.sh
      install: sh .travis/install.sh
      script: sh .travis/run_tests.sh
    - compiler: clang
      before_install: sh .travis/before_install.sh
      install: sh .travis/install.sh
      script: sh .travis/run_tests.sh
