language: cpp
compiler:
  - gcc
  - clang
dist: xenial
#include:
#  - python: "3.7"
#pyenv: python3.7

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - pyenv global system 3.7

install: 
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt install libboost-dev

script: 
  - mkdir -p build
  - cd build
  - cmake ..
  - make all
  - ./test/dataset_test
