version: '{build}'
os: Visual Studio 2019
branches:
  only:
  - visual_studio_build # TODO change to master 

matrix:
  fast_finish: true

platform:
  - x64

configuration:
  - Release

install:
- set PATH=%PATH%;c:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\
- cd %APPVEYOR_BUILD_FOLDER%
- git submodule update --init
- mkdir build
- cd build%

build_script:
- cmake -G "Visual Studio 16 2019" -A x64 -DPYTHON_EXECUTABLE="C:/Python36-x64/python.exe" -DCMAKE_INSTALL_PREFIX=../install ..
- cmake --build . --config %CONFIGURATION% --target install all-tests

test_script:
- ctest -VV 
- C:\Python36-x64\python.exe -m pip install -r ..\python\requirements.txt
- set PYTHONPATH=%PYTHONPATH%;..\install
- cd ..\python
- C:\Python36-x64\python.exe -m pytest
