package:
  name: scipp
  # Get version number from most recent Git tag
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - cmake
    - gxx_linux-64 7.3.*
    - clangxx_osx-64 4.0.*
    - git
    - python {{ python }}
  run:
    - ipywidgets 7.*
    - numpy {{ numpy }}
    - plotly 3.*
    - python {{ python }}

build:
  # Build number is number of Git commits since last tag, if that fails use 0
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

about:
  home: https://scipp.readthedocs.io/en/latest/
  license: GPLv3
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.readthedocs.io/en/latest/
