package:
  name: scipp
  # Get version number from most recent Git tag
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - cmake
    - gxx_linux-64 7.3.* [linux64]
    - git
    - python {{ python }}
    - ninja
  run:
    - numpy {{ numpy }}
    - python {{ python }}
    - appdirs
    - python-configuration
    - pyyaml

test:
  import:
    - scipp
  commands:
    # Run  Python tests from external source directory
    - python -m pip install -r {{ environ.get('SRC_DIR') }}/python/requirements.txt
    - python -m pytest -v {{ environ.get('SRC_DIR') }}/python

build:
  # Build number is number of Git commits since last tag, if that fails use 0
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - CC
    - CXX
    - OSX_VERSION
    - CONDA
    - SRC_DIR

about:
  home: https://scipp.readthedocs.io/en/latest/
  license: GPLv3
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.readthedocs.io/en/latest/
